name: Django Docker Build & Push

on:
  push:
    branches:
      - main # 当主分支有push时触发
  workflow_dispatch: # 允许手动触发

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: . # 使用当前目录作为构建上下文
          file: Dockerfile # 指定Dockerfile的位置
          push: true # 推送镜像到registry
          tags: |
            Accccc90/Litma:latest # 替换为你的Docker用户名和镜像名
          build-args: |
            DJANGO_SETTINGS_MODULE=Litma.settings # 如果Dockerfile中有使用环境变量构建参数

      - name: Image digest
        if: success() # 只在成功时运行
        run: echo ${{ steps.docker_build.outputs.digest }}